name: f1-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - fastf1==3.7.1
    - pandas==2.2.2
    - numpy==1.26.2
    - scikit-learn==1.2.3
    - xgboost==1.7.6
    - shap==0.42.1
    - matplotlib==3.8.1
    - scipy==1.11.1
    - joblib==1.3.1
    - python-dateutil
