name: Publish Presentation (GH Pages)

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          if [ -f requirements_pinned.txt ]; then pip install -r requirements_pinned.txt; fi
      - name: Run tests
        run: python3 -m pytest -q
      - name: Run demo (generate presentation)
        run: python3 scripts/run_demo.py
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./presentation
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
