name: Showcase

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          if [ -f requirements_pinned.txt ]; then pip install -r requirements_pinned.txt; fi
      - name: Run tests
        run: python3 -m pytest -q
      - name: Run demo
        run: python3 scripts/run_demo.py
      - name: Upload presentation
        uses: actions/upload-artifact@v4
        with:
          name: presentation
          path: presentation
      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: manifest
          path: artifacts/manifest.json
